const books = [
  {
    id: 1,
    image: "https://res.cloudinary.com/dqqobhvnd/image/upload/v1711399408/Online-library/book1_wd3xly.png",
    title: "Simple Way Of Piece Life",
    author: "Armor Ramsey",
    price: "$ 40.00",
  },
  {
    id: 2,
    image: "https://res.cloudinary.com/dqqobhvnd/image/upload/v1711399399/Online-library/catalog2_exreox.png",
    title: "Great Travel At Desert",
    author: "Sanhii Howly",
    price: "$ 38.00",
  },
  {
    id: 3,
    image: "https://res.cloudinary.com/dqqobhvnd/image/upload/v1711399402/Online-library/catalog3_njzojo.png",
    title: "The Lade beauty Scarlett",
    author: "Arthur Doyle",
    price: "$ 45.00",
  },
  {
    id: 4,
    image: "https://res.cloudinary.com/dqqobhvnd/image/upload/v1711399412/Online-library/book2_c4lwtv.png",
    title: "Great travel at desert",
    author: "Sanchit Howdy",
    price: "$ 38.00",
  },
  {
    id: 5,
    image: "https://res.cloudinary.com/dqqobhvnd/image/upload/v1711399405/Online-library/catalog5_y9pwce.png",
    title: "The hypocrite world",
    author: "Sophia Hill",
    price: "$ 45.00",
  },
  {
    id: 6,
    image: "https://res.cloudinary.com/dqqobhvnd/image/upload/v1711399415/Online-library/book3_oiguo9.png",
    title: "The lady beauty scarlett",
    author: "Arthur Doyle",
    price: "$ 45.00",
  },
  {
    id: 7,
    image: "https://res.cloudinary.com/dqqobhvnd/image/upload/v1711399418/Online-library/book4_kublol.png",
    title: "Once upon a time",
    author: "Killen Marry",
    price: "$ 35.00",
  },
  {
    id: 8,
    image: "https://res.cloudinary.com/dqqobhvnd/image/upload/v1711399408/Online-library/book1_wd3xly.png",
    title: "The road to recognition",
    author: "Barry Feldman",
    price: "$ 49.00",
  },
  {
    id: 9,
    image: "https://res.cloudinary.com/dqqobhvnd/image/upload/v1711399399/Online-library/catalog2_exreox.png",
    title: "The mind connection",
    author: "Joyce Meyer",
    price: "$ 41.00",
  },
  {
    id: 10,
    image: "https://res.cloudinary.com/dqqobhvnd/image/upload/v1711399418/Online-library/book4_kublol.png",
    title: "Battlefield of the mind",
    author: "Joyce Meyer",
    price: "$ 41.50",
  },
  {
    id: 11,
    image: "https://res.cloudinary.com/dqqobhvnd/image/upload/v1711399412/Online-library/book2_c4lwtv.png",
    title: "Great travel at desert",
    author: "Sanchit Howdy",
    price: "$ 38.00",
  },
  {
    id: 12,
    image: "https://res.cloudinary.com/dqqobhvnd/image/upload/v1711399405/Online-library/catalog5_y9pwce.png",
    title: "The hypocrite world",
    author: "Sophia Hill",
    price: "$ 45.00",
  },
  {
    id: 13,
    image: "https://res.cloudinary.com/dqqobhvnd/image/upload/v1711399418/Online-library/book4_kublol.png",
    title: "Once upon a time",
    author: "Killen Marry",
    price: "$ 35.00",
  },
  {
    id: 14,
    image: "https://res.cloudinary.com/dqqobhvnd/image/upload/v1711399408/Online-library/book1_wd3xly.png",
    title: "The road to recognition",
    author: "Barry Feldman",
    price: "$ 49.00",
  },
  {
    id: 15,
    image: "https://res.cloudinary.com/dqqobhvnd/image/upload/v1711399402/Online-library/catalog3_njzojo.png",
    title: "The Lade beauty Scarlett",
    author: "Arthur Doyle",
    price: "$ 45.00",
  },
  {
    id: 16,
    image: "https://res.cloudinary.com/dqqobhvnd/image/upload/v1711399399/Online-library/catalog2_exreox.png",
    title: "The mind connection",
    author: "Joyce Meyer",
    price: "$ 41.00",
  },
];

module.exports = books;
